// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rg-km/final-project-engineering-4/backend/domain (interfaces: DetailTugasRepository,DetailTugasUseCase)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockDetailTugasRepository is a mock of DetailTugasRepository interface.
type MockDetailTugasRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDetailTugasRepositoryMockRecorder
}

// MockDetailTugasRepositoryMockRecorder is the mock recorder for MockDetailTugasRepository.
type MockDetailTugasRepositoryMockRecorder struct {
	mock *MockDetailTugasRepository
}

// NewMockDetailTugasRepository creates a new mock instance.
func NewMockDetailTugasRepository(ctrl *gomock.Controller) *MockDetailTugasRepository {
	mock := &MockDetailTugasRepository{ctrl: ctrl}
	mock.recorder = &MockDetailTugasRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDetailTugasRepository) EXPECT() *MockDetailTugasRepositoryMockRecorder {
	return m.recorder
}

// MockDetailTugasUseCase is a mock of DetailTugasUseCase interface.
type MockDetailTugasUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDetailTugasUseCaseMockRecorder
}

// MockDetailTugasUseCaseMockRecorder is the mock recorder for MockDetailTugasUseCase.
type MockDetailTugasUseCaseMockRecorder struct {
	mock *MockDetailTugasUseCase
}

// NewMockDetailTugasUseCase creates a new mock instance.
func NewMockDetailTugasUseCase(ctrl *gomock.Controller) *MockDetailTugasUseCase {
	mock := &MockDetailTugasUseCase{ctrl: ctrl}
	mock.recorder = &MockDetailTugasUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDetailTugasUseCase) EXPECT() *MockDetailTugasUseCaseMockRecorder {
	return m.recorder
}
