// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rg-km/final-project-engineering-4/backend/domain (interfaces: JadwalRepository,JadwalUseCase)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockJadwalRepository is a mock of JadwalRepository interface.
type MockJadwalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJadwalRepositoryMockRecorder
}

// MockJadwalRepositoryMockRecorder is the mock recorder for MockJadwalRepository.
type MockJadwalRepositoryMockRecorder struct {
	mock *MockJadwalRepository
}

// NewMockJadwalRepository creates a new mock instance.
func NewMockJadwalRepository(ctrl *gomock.Controller) *MockJadwalRepository {
	mock := &MockJadwalRepository{ctrl: ctrl}
	mock.recorder = &MockJadwalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJadwalRepository) EXPECT() *MockJadwalRepositoryMockRecorder {
	return m.recorder
}

// MockJadwalUseCase is a mock of JadwalUseCase interface.
type MockJadwalUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockJadwalUseCaseMockRecorder
}

// MockJadwalUseCaseMockRecorder is the mock recorder for MockJadwalUseCase.
type MockJadwalUseCaseMockRecorder struct {
	mock *MockJadwalUseCase
}

// NewMockJadwalUseCase creates a new mock instance.
func NewMockJadwalUseCase(ctrl *gomock.Controller) *MockJadwalUseCase {
	mock := &MockJadwalUseCase{ctrl: ctrl}
	mock.recorder = &MockJadwalUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJadwalUseCase) EXPECT() *MockJadwalUseCaseMockRecorder {
	return m.recorder
}
