name: Build Server
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Setup Go
          uses: actions/setup-go@v3
          with:
            go-version: '1.18'
        - name: Run Build
          run: env GOOS=windows GOARCH=amd64 go build -o server.exe backend/app/main.go
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add .
            git commit -m "build: build server" -a
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
